2024-12-24 01:40:54,219 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\UrbanArete\pythonProject\Module_12\tests_12_4.py", line 23, in test_run
    runner = Runner(2)
  File "D:\UrbanArete\pythonProject\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-24 01:40:54,219 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\UrbanArete\pythonProject\Module_12\tests_12_4.py", line 12, in test_walk
    runner = Runner("Вася", -5)
  File "D:\UrbanArete\pythonProject\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
